### ISSUE TITLE
FEAT: Gamepidgeon alternative

### ISSUE THREAD

**Issue by theamazing0** [thepurplebubble/matrix-client#17]
### What feature would you like to see?

Offering mutiplayer game(s) similar to iMessage's gamepidgeon or Discord's activities could attract people to use Purple Bubble.

**Comment by aramshiva** [comment]
Gamepigeon is downloading an app on your phone. Has nothing to do with SMS. iOS does not allow you to download apps from any app other than the App Store.

**Comment by theamazing0** [comment]
I don't think you understood the feature request correctly. I didn't mean a seperate app. I meant a multiplayer game feature built in, _similar_ to games from gamepidgeon and Discord's activities.

> Has nothing to do with SMS.

It has to do with being an alternative to imessage. While gamepidgeon is not included in imessage, the fact that imessage supports gamepidgeon is something imessage would have over purple bubble.

> iOS does not allow you to download apps from any app other than the App Store.

Thats not really relevant for this feature. It isnt asking for third party apps to add games to Purple Bubble, its asking for multiplayer games _included in_ the app.

Please reopen the feature request if you have no other objections.

**Comment by theamazing0** [comment]
This def isn't a core feature, but it could be an important feature to making it an alternative to imessage.

**Comment by aramshiva** [comment]
Matrix doesnt allow this either if I am not mistaken.

**Comment by theamazing0** [comment]
Reposting from Slack for future purposes:

> Messaging data doesn't have to be actual messages

> https://thirdroom.io/landing

> well then it would require both the recipient and the receivee to be on  purple bubble

> atm it doesn't make sense until we actually build the client. I think we will reopen after we build the client as a enchantment

> Yeah
