### ISSUE TITLE
Selection of language for client

### ISSUE THREAD

**Issue by theamazing0** [thepurplebubble/matrix-client#8]
### What would you like to share?

A language needs to be chosen for the app so development can start. The following criteria (In order of importance) should be used to find the best language to use.

1. **Cross-platform support:** The language needs to support Windows, macOS, Linux, Android, and iOS.
2. **Matrix Sdk compatibility:** Ideally, the chosen language should have a good [matrix sdk](https://matrix.org/ecosystem/sdks/), making it easier to implement matrix features. 
3. **Difficulty of language:** The language chosen should not be too hard to learn, and/or should have developers that already have some familiarity with it.

**Comment by theamazing0** [comment]
With this criteria, I think flutter would be a good choice.

**Comment by theamazing0** [comment]
Svelte was selected

**Comment by reesericci** [comment]
*SvelteKit
